### ISSUE TITLE
Contributing MD and building files. 

### ISSUE THREAD

**Issue by michaelBenin** [rosszurowski/vanilla-fitvids#4]
Hi,

Recently I made a pr and there was no command to build the UMD version of the files.

**Comment by rosszurowski** [comment]
Ah, my bad. The commands are contained within the [`Makefile`](https://github.com/rosszurowski/vanilla-fitvids/blob/master/Makefile), but it's not documented anywhere.

I've added [a brief note](https://github.com/rosszurowski/vanilla-fitvids#contributing) to the readme.
